export const applicationRows = [
  {
    role: "Senior Software Engineer",
    company: "Acme AI",
    status: "In Progress",
    lastActivity: "Today, 9:42 AM",
    progress: 75,
    source: "acme_career_portal.pdf",
  },
  {
    role: "Software Engineer II",
    company: "Northwind Labs",
    status: "Ready to Submit",
    lastActivity: "Yesterday, 4:15 PM",
    progress: 100,
    source: "northwind_application.pdf",
  },
  {
    role: "Full Stack Developer",
    company: "BluePeak Systems",
    status: "Submitted",
    lastActivity: "May 14, 2026",
    progress: 100,
    source: "bluepeak_application.pdf",
  },
  {
    role: "Backend Engineer",
    company: "DataForge",
    status: "In Progress",
    lastActivity: "May 13, 2026",
    progress: 60,
    source: "dataforge_application.pdf",
  },
  {
    role: "Software Engineer",
    company: "FutureTech",
    status: "Withdrawn",
    lastActivity: "May 10, 2026",
    progress: 40,
    source: "futuretech_application.pdf",
  },
];

export const fillSections = [
  {
    section: "Personal Information",
    fields: "7 / 7",
    coverage: 100,
    status: "Reviewed",
    confidence: "High",
  },
  {
    section: "Contact Information",
    fields: "5 / 5",
    coverage: 100,
    status: "Reviewed",
    confidence: "High",
  },
  {
    section: "Work Experience",
    fields: "6 / 8",
    coverage: 75,
    status: "Review Needed",
    confidence: "Medium",
  },
  {
    section: "Education",
    fields: "3 / 4",
    coverage: 75,
    status: "Review Needed",
    confidence: "Medium",
  },
  {
    section: "Skills",
    fields: "10 / 10",
    coverage: 100,
    status: "Reviewed",
    confidence: "High",
  },
  {
    section: "Additional Questions",
    fields: "2 / 6",
    coverage: 33,
    status: "Review Needed",
    confidence: "Low",
  },
  {
    section: "EEO Information",
    fields: "0 / 4",
    coverage: 0,
    status: "Pending",
    confidence: "-",
  },
];
